version: '3.3'
services:
  api:
    build: .
    command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
      - db
    container_name: jnv-api

  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
    - "5432:5432"
    container_name: jnv-postgres

volumes:
  postgres_data:

